### ISSUE TITLE
talibrt CCI gives different result than talib

### ISSUE THREAD

**Issue by mdukaczewski** [trufanov-nok/ta-lib-rt#14] opened 2020-12-07 20:06 UTC
```
import talibrt
import talib
import numpy as np

timeperiod = 8
data = [1.1] *timeperiod

lows = np.asarray(data)
highs = lows.copy()
closes = lows.copy()

_, state = talibrt.CCI_StateInit(timeperiod=timeperiod)
_, talibrt_ret = talibrt.CCI_BatchState(state, highs, lows, closes)
talib_ret = talib.CCI(highs, lows, closes, timeperiod=timeperiod)
print("talibrt", talibrt_ret[-1], "talib", talib_ret[-1])

```
returns
`talibrt 0.0 talib 66.66666666666667`

**Comment by trufanov-nok** [comment] 2020-12-08 03:34
Hm... When I've heard about CCI i started from googling if I reported a bug about it bcs CCI sounds familiar, but I found nothing.   
The problem is that CCI [stores](https://github.com/trufanov-nok/ta-lib-rt/blob/master/ta-lib-rt/c/src/ta_func/ta_CCI.c#L260) average of input data which is `(1.1+1.1+1.1)/3=1.1` then calculates average for timeperiod among them, which is exactly the same 1.1. Then calculates sum of stdabs of this average and previous data. Which is supposed to be 0. And after a few other calculations it [prints](https://github.com/trufanov-nok/ta-lib-rt/blob/master/ta-lib-rt/c/src/ta_func/ta_CCI.c#L279) a result:
```
      if( (tempReal != 0.0) && (tempReal2 != 0.0) )
      {
         outReal[outIdx++] = tempReal/(0.015*(tempReal2/optInTimePeriod));
      }
      else
         outReal[outIdx++] = 0.0;
```

The problem is that average isn't a zero. It's a 2.220446049250313e-16 due to float numbers implementation in CPU. Which is pretty close to zero but true in `if (val != 0.0)`. You can try in python:
```
>>> a = 1.1
>>> a
1.1
>>> a = a + a + a + a + a + a + a
>>> a
7.699999999999999
>>> b = a/7
>>> b
1.0999999999999999
>>> 1.1 - b
2.220446049250313e-16
```

And at the end talib gives you
```
>>> 2.220446049250313e-16 / (0.015*(1.5543122344752192e-15 / 7))
66.66666666666667
```

In _State implementation of CCI I have changed the [output condition](https://github.com/trufanov-nok/ta-lib-rt/blob/master/ta-lib-rt/c/src/ta_func/ta_CCI.c#L439) to:
```
   if( (std_fabs(lastValue) > 1e-13) && (std_fabs(sum) > 1e-13) )
   {
      VALUE_HANDLE_DEREF(outReal) = lastValue/(0.015*(sum/STATE.optInTimePeriod));
   }
   else
       VALUE_HANDLE_DEREF(outReal) = 0.0;
```
And it's going to the `else` operations bcs values are smaller than 1e-13.   
So, we have two results. 0.0 and 66.66 is quite a different thing.   

It looks like I catched this issue, considered it as a bug, fixed in CCI State function but not in the original. Most probably I was going to post a bugreport to the original project and wait for reply. But for some reason I can't find this bugreport now. Perhaps I forgot to post it. They are not replied for years anyway.   
So, what do you think about that? Shall I keep the original code untouched?

**Comment by mdukaczewski** [comment] 2020-12-08 13:17
Thanks for the quick reply. If you found a bug in the original library then I think it's good you fixed it.
However, I think it would be useful to know what changes to the original library logic were made, so there should be at least a note on the project wiki. I know about the changes you made for period = 1 and the CCI, but there are probably more.
For example, I had a model trained for on talib and I wanted to use it with talibrt, so such changes are important to me. I guess I'm not the only one. And such changes that are not described anywhere can cause consternation. The ideal solution in my opinion would be to keep the current version as the default, but introduce an additional flag, e.g. #define TALIB_LOGIC_COMPATIBLE and keep both versions in the code.

Finally, I would like to thank you for your work on this library and its publication. If you provide a bitcoin address, I will give you a donation.

**Closed** 2020-12-12 09:46 UTC

**Comment by trufanov-nok** [comment] 2020-12-15 02:26
> Finally, I would like to thank you for your work on this library and its publication. If you provide a bitcoin address, I will give you a donation.  

I guess I was finally able to create a request address in Bitcoin Core: bc1qrp7t9uakfhrst428qyuqwxjy4qjejrl6ydws36

**Comment by trufanov-nok** [comment] 2020-12-15 12:56
Have just got it! Thanks a lot for your support!

**Comment by mario4tier** [comment] 2025-01-07 20:16
Hi @trufanov-nok,

First, thanks for the good dev work you kept doing all these years.

I am allocating some time in 2025 to resolve most backlogs and "automate" TA-Lib testing/packaging/releasing. So now would be a good time if you would like to either submit a PR for this or even better... I can give you write permission to TA-Lib itself to make you one of the official maintainer (you clearly have the expertise to do it).

Would prefer you do it so you get the credit for it... but if you are too busy, just tell me and I will make the change.

\Mario Fortier

**Comment by trufanov-nok** [comment] 2025-01-09 08:27
Hi @mario4tier 
It's vice versa for me - no time in 2025 at all. Perhaps I'll make some PR this weekend, but feel free to take any code you consider to be useful for the original TA-Lib library in any case.

**Comment by mario4tier** [comment] 2025-01-10 20:56
@trufanov-nok Thanks for the update. 

I will stand back until January 14, giving you time to submit PR (may be)... but don't feel obligated... I fully understand about not having time for extra stuff for 1-2 years or in my case >10 :laughing:

Starting on January 14, I will "carry the flag" to integrate your remaining proposed fixes. They are well investigated and documented, so thanks again for that.
